version: '3.4'

services:
  rest-with-asp-net:
    image: rest_with_asp_net_udemy:dev
    container_name: "RestWithASP-NET"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RestWithASP-NET"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\tcxdr\OneDrive\Área de Trabalho\PROG\RestWithASP-NET\RestWithASP-NET\07_RestWithASP-NET-DOCKER\RestWithASP-NET\RestWithASP-NET:/app:rw
      - C:\Users\tcxdr\OneDrive\Área de Trabalho\PROG\RestWithASP-NET\RestWithASP-NET\07_RestWithASP-NET-DOCKER\RestWithASP-NET:/src:rw
      - C:\Users\tcxdr\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\tcxdr\.nuget\packages:/.nuget/packages:ro
      - C:\Users\tcxdr\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\tcxdr\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\tcxdr\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\tcxdr\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/RestWithASP-NET.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true